# Sparse Matrix

In [1]:
import numpy as np
from scipy.sparse import csc_matrix

In [5]:
row=np.array([0,1,2])
col=np.array([1,2,0])
data=np.array([9,4,18])
A = csc_matrix((data,(row, col)),shape = (3, 3))
A.toarray()

array([[ 0,  9,  0],
       [ 0,  0,  4],
       [18,  0,  0]], dtype=int32)

In [7]:
row1=np.array([1,0,2])
col1=np.array([0,1,2])
data1=np.array([5,6,9])
B = csc_matrix((data1,(row1, col1)),shape = (3, 3))
B.toarray()

array([[0, 6, 0],
       [5, 0, 0],
       [0, 0, 9]], dtype=int32)

In [8]:
AB=A.multiply(B)
AB.toarray()

array([[ 0, 54,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int32)